#!/usr/bin/env groovy //可以在PATH目录中查找 并用groovy解释

pipeline {
    agent any

    stages {
        stage('初始化') {
            steps {
                println "初始化"
            }
        }
        stage('代码扫描阶段') {
            steps {
                println "代码扫描阶段"
            }
        }
        stage('单元测试阶段') {
            steps {
                println "代码扫描阶段"
            }
        }
        stage('项目构建阶段') {
            steps {
                println "代码扫描阶段"
            }
        }
        stage('部署阶段') {
            steps {
                println "代码扫描阶段"
            }
        }
    }
}